consolidate-commits = true
shared-version = true
tag-name = "v{{version}}"
tag-prefix = "v"
pre-release-commit-message = "chore(release): prepare {{version}}"
pre-release-hook = ["sh", "-c", "git cliff --config cliff.toml --output CHANGELOG.md"]
publish = false
allow-branch = ["main"]
