base_poll_seconds = 1800
id_prefix = "slashdot"
category = "tech"
provenance = "slashdot"
tags = [
    "tech",
]
language = "en"
content_type = "xml"

[[feeds]]
id = "main"
url = "http://rss.slashdot.org/Slashdot/slashdotMain"
