base_poll_seconds = 180
id_prefix = "xkcd"
category = "comics"
provenance = "xkcd"
tags = [
    "comics",
]
language = "en"
content_type = "xml"

[[feeds]]
id = "main"
url = "https://xkcd.com/rss.xml"
