# Exchanges

base_poll_seconds = 1000
id_prefix = "goldmansachs"
category = "podcasts"
provenance = "goldmansachs"
tags = [
    "podcasts",
]
language = "en"
content_type = "xml"

[[feeds]]
id = "exchanges"
url = "https://feeds.megaphone.fm/GLD9218176758"

# The Markets


[[feeds]]
id = "the-markets"
url = "https://feeds.megaphone.fm/GLD9322922848"

#  Talks at GS


[[feeds]]
id = "talks-at-gs"
url = "https://feeds.megaphone.fm/GLD3069230077"
